# Generated by Django 2.0 on 2018-02-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='dctv_channel',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='includes',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='event',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='speakers',
            field=models.ManyToManyField(null=True, to='event_manager.Speaker'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='sptitle',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='twitter',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='link',
            field=models.URLField(blank=True, max_length=2048),
        ),
    ]
