# Generated by Django 2.0 on 2018-02-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0003_auto_20180210_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='speakers',
            field=models.ManyToManyField(to='event_manager.Speaker'),
        ),
    ]
