# Generated by Django 2.0 on 2018-06-14 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0005_auto_20180605_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='conference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event_manager.Conference'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event_manager.EventType'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event_manager.Location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='conference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event_manager.Conference'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='conference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event_manager.Conference'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='conference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event_manager.Conference'),
        ),
    ]
