# Generated by Django 2.0 on 2018-06-17 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0007_auto_20180614_0122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village', models.CharField(max_length=1024)),
                ('conference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event_manager.Conference')),
            ],
        ),
    ]
