# Generated by Django 2.0 on 2018-06-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0009_auto_20180617_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default='2018-01-01T01:00:00-00:00'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default='2018-01-01T00:00:00-00:00'),
        ),
    ]
