# Generated by Django 2.0 on 2018-06-23 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0010_auto_20180618_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='conference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event_manager.Conference'),
        ),
    ]
