# Generated by Django 2.0 on 2018-06-28 21:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0012_conference_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conference',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
