# Generated by Django 2.0.6 on 2018-06-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0014_auto_20180628_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='color',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
