# Generated by Django 2.0.6 on 2018-07-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0015_eventtype_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='timezone',
            field=models.CharField(default='America/Los_Angeles', max_length=32),
        ),
    ]
