# Generated by Django 2.0.6 on 2019-08-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0017_article_faq_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='hotel',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
