# Generated by Django 2.2.7 on 2020-07-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0018_location_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='tags',
            field=models.CharField(max_length=256, null=True),
        ),
    ]

