# Generated by Django 2.2.7 on 2020-07-31 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0019_auto_20200731_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='tags',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
