# Generated by Django 2.2.7 on 2020-08-03 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0021_auto_20200801_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='eventdescriptionfooter',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='youtube_url',
            field=models.CharField(default='', max_length=256),
        ),
    ]
