# Generated by Django 2.2.7 on 2020-08-05 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0022_auto_20200803_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='eventdescriptionfooter',
            field=models.TextField(blank=True),
        ),
    ]
