# Generated by Django 3.0.8 on 2020-08-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0023_location_eventdescriptionfooter'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='tags',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
